name: dart_lame
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  ffigen: ^6.1.2

ffigen:
  name: 'LameBindings'
  description: 'Bindings to LAME'
  output: 'lib/src/generated/bindings.g.dart'
  headers: 
    entry-points:
      - 'lame/include/lame.h'
  preamble: |
    // ignore_for_file: always_specify_types
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
  comments:
    style: any
    length: full